### ISSUE TITLE
Keybinding?

### ISSUE THREAD

**Issue by kuator** [Xuyuanp/scrollbar.nvim#1]
Would it be possible to add a mapping to control scrollbar with keyboard?

**Comment by Xuyuanp** [comment]
What do you want to control?

**Comment by kuator** [comment]
The scrollbar itself. If it's a window, one could jump to it with ctrl-w ctrl-h, and then scroll the buffer with j and k.

**Comment by Xuyuanp** [comment]
The window is not focusable. You could only jump into it with win id

**Comment by kuator** [comment]
Ohh, I see, thank you for explanation
