### ISSUE TITLE
After :enew, the scrollbar remains and cannot be cleared

### ISSUE THREAD

**Issue by delphinus** [Xuyuanp/scrollbar.nvim#14]
1. open some file. `:e ~/.config/nvim/init.vim`
   * Now you can see the scrollbar moving.
2. `:enew`
   * The scrollbar still remains but does not work.

`:enew` makes a new buffer and clear all buffer variables. So `b:scrollbar_state` already disappeared and this plugin cannot access the window ID of the existent scrollbar.

What can I do for this? (can remove lone scrollbars after `:enew`?)

**Comment by Xuyuanp** [comment]
call `clear` when `BufLeave`

**Comment by delphinus** [comment]
Cool!
