### ISSUE TITLE
Update scroll bar on <C-e> or z<CR>

### ISSUE THREAD

**Issue by toyboot4e** [Xuyuanp/scrollbar.nvim#2]
Thank you for your incredible work! I'm feeling more like I'm home seeing the scroll bar.

Seems like the scroll bar position is not updated when pressing `<C-e>`, `<C-y>`, `z<CR>`, or `z-`. Can it be automated?

Edit: in a way that doesn't change key mappings. Thanks!

**Comment by Xuyuanp** [comment]
Have you remapped these keys?
Works well for me.

**Comment by toyboot4e** [comment]
I guess no.

Is the scroll bar position calculated based on cursor position, not scroll amount? Then it makes sense.

**Comment by Xuyuanp** [comment]
Yes, it's based on the cursor line.

**Comment by toyboot4e** [comment]
Ok, thank you!
