### ISSUE TITLE
Multiple scrollbars appeared when `go to definition`.

### ISSUE THREAD

**Issue by RunningIkkyu** [Xuyuanp/scrollbar.nvim#21]
## Steps to reproduce the bug

Using Neovim LanguageClient to go to definition of a function, both the old file's scrollbar and the new file's srallbar are staying on the right side.

## Resulting and expected behaviour

Only one scrollbar exists.

## Screen recording or screenshot

![image](https://user-images.githubusercontent.com/31848542/119285737-4fbe5000-bc75-11eb-9fba-072c07ed8dea.png)

![image](https://user-images.githubusercontent.com/31848542/119285770-64024d00-bc75-11eb-91f8-4879930b40d6.png)

## System information

- Operating system: ubuntu 20.04
- Neovim version: v0.5.0

**Comment by RunningIkkyu** [comment]
Solving that by add auto command to vim config: 

```vim
autocmd WinLeave,BufLeave,BufWinLeave,FocusLost            * silent! lua require('scrollbar').clear()
```

**Comment by RunningIkkyu** [comment]
Create a PR for this issue. Just update the autocmd in the doc. #22

**Comment by Xuyuanp** [comment]
Thanks for your great PR!
