### ISSUE TITLE
Option to only show on mouse scroll?

### ISSUE THREAD

**Issue by pinpox** [Xuyuanp/scrollbar.nvim#3]
Small feature request:

Would it be possible to show it only when I'm scrolling with the mouse wheel? 
When using vim as a file viewer I would love a scrollbar.

**Comment by Xuyuanp** [comment]
Yes.
```vim
autocmd CursorHold * silent! lua require('scrollbar').clear()
```

**Comment by Melkster** [comment]
I had problems getting this working and was able to boil it down to the configuration below. It seems that [vim-airline-clock](https://github.com/enricobacis/vim-airline-clock) (together with [vim-airline](https://github.com/vim-airline/vim-airline)) is the problem. For some reason the scrollbar never goes away on `CursorHold` with the following configuration. If I remove `vim-airline-clock` the scrollbar dissapears on `CursorHold` as expected.

```vim
call plug#begin('~/.vim/bundle')
Plug 'bling/vim-airline'
Plug 'enricobacis/vim-airline-clock'
Plug 'Xuyuanp/scrollbar.nvim'
call plug#end()

augroup scrollbar
  autocmd!
  autocmd BufEnter    * silent! lua require('scrollbar').show()
  autocmd BufLeave    * silent! lua require('scrollbar').clear()

  autocmd CursorMoved * silent! lua require('scrollbar').show()
  autocmd VimResized  * silent! lua require('scrollbar').show()

  autocmd FocusGained * silent! lua require('scrollbar').show()
  autocmd FocusLost   * silent! lua require('scrollbar').clear()

  autocmd CursorHold  * silent! lua require('scrollbar').clear()
augroup end

set updatetime=500
```

**Comment by Xuyuanp** [comment]
set `g:airline#extensions#clock#updatetime` to a value larger than `updatetime`

**Comment by Melkster** [comment]
Thanks, that solved it!

How would I go about getting the scrollbar to stay longer than `updatetime`? I use some other plugins that work better with a low `updatetime` value, while I would like the scrollbar to stay visible for longer before being cleared. Would it be possible to tweak the line

```vim
autocmd CursorHold  * silent! lua require('scrollbar').clear()
```

in some way to add some (non-blocking) delay before calling `clear()`? I'm not yet familiar with the Lua API.

**Comment by Xuyuanp** [comment]
```vim
 function! MyScrollbarShow() abort
    let l:winnr = 0
    let l:bufnr = bufnr()
    if exists('b:scrollbar_timer_id') | call timer_stop(b:scrollbar_timer_id) | endif
    call luaeval('require("scrollbar").show(_A[1], _A[2])', [l:winnr, l:bufnr])
    let b:scrollbar_timer_id = timer_start(4000, {-> luaeval('require("scrollbar").clear(_A[1], _A[2])', [l:winnr, l:bufnr])}, {'repeat': 1})
endfunction
```

Use the function above instead of the default `show`.
PS. This function has not been fully tested. 
PS. Please perform an update firstly, I just pushed some bugfixes.

Maybe this should be a feature integrated.

**Comment by Xuyuanp** [comment]
eg.
```vim
autocmd CursorMoved * call MyScrollbarShow()
```

The trigger on `CursorHold` should be removed.

**Comment by Melkster** [comment]
@Xuyuanp Thanks, I'll give it a try!

**Comment by jeromedalbert** [comment]
Here's what I did to show the scrollbar only when the screen itself scrolls:

```viml
augroup configure_scrollbar
  autocmd!
  autocmd CursorMoved * call ShowScrollbar()
  autocmd CursorHold,BufLeave,FocusLost,VimResized,QuitPre * silent! lua require('scrollbar').clear()
augroup end
set updatetime=500

function! ShowScrollbar()
  let first_visible_linenum = line('w0')
  if !exists('b:previous_first_visible_linenum')
    let b:previous_first_visible_linenum = first_visible_linenum
    return
  endif
  if first_visible_linenum != b:previous_first_visible_linenum
    silent! lua require('scrollbar').show()
  end
  let b:previous_first_visible_linenum = first_visible_linenum
endfunction

" Optional
function! OnBufEnter()
  if !exists('b:previous_first_visible_linenum')
    let b:previous_first_visible_linenum = line('w0')
  endif
endfunction

augroup general_autocommands
  autocmd!
  autocmd BufEnter * call OnBufEnter()
augroup end
```
