### ISSUE TITLE
Change suggested autocommand

### ISSUE THREAD

**Issue by rcarriga** [Xuyuanp/scrollbar.nvim#5]
Awesome work, this is a really cool plugin!

I just have a small suggestion for the README. Using `BufEnter` and `BufLeave` events means that when using the `split` and `vsplit` commands without any arguments, the bar doesn't update as the same buffer is used but in the new window. Replacing these with the `WinEnter` and `WinLeave` events fixes the issue.

Like I said just a minor thing, otherwise thanks a million!

**Comment by Xuyuanp** [comment]
Thanks for your suggestion!

Can you send a pr?

**Comment by Melkster** [comment]
Also, all the `autocmd` events can be combined into the same lines which drastically reduces the number of lines in `:h scrollbar-config` like so:

```vim
" -- scrollbar --
augroup your_config_scrollbar_nvim
  autocmd!
  autocmd WinEnter,FocusGained,CursorMoved,VimResized * silent! lua require('scrollbar').show()
  autocmd WinLeave,FocusLost                          * silent! lua require('scrollbar').clear()
augroup end
```

**Comment by Melkster** [comment]
Perhaps this should be updated in [`:help scrollbar-config`](https://github.com/Xuyuanp/scrollbar.nvim/blob/7cf0498dfc1e15402895b2820b7a74a832fac164/doc/scrollbar.txt#L30) as well?
