### ISSUE TITLE
Scrollbar clutters :oldfiles

### ISSUE THREAD

**Issue by Melkster** [Xuyuanp/scrollbar.nvim#6]
First of all, I just wanna say that this little plugin is awesome!

Anyway, after trying this plugin out for a while and running `:oldfiles` I see a lot of `~/scrollbar_x` files where `x` is a digit.

I also noticed that other plugins that show me recently used files seem to have been cleared of most of my files.

**Comment by Xuyuanp** [comment]
I just pushed a fix.
Only one scrollbar-buffer will be created for each buffer. You still will see `scrollbar_0` and `scrollbar_1`, but maybe not too much. It determined by the number of buffers you open in a single session.
