### ISSUE TITLE
Rewrite in in vim script

### ISSUE THREAD

**Issue by wsdjeg** [Xuyuanp/scrollbar.nvim#9]
Hi, @Xuyuanp, Thanks for sharing this project, I like the idea of this project, and I want to use it in @SpaceVim. But `+lua` support is not always enabled in my env, so I want to [rewrite it into vim script](https://github.com/SpaceVim/SpaceVim/pull/3826).

BTW, just see your profile, you are chinese too. feel free to join our [vim group](http://gitter.im/SpaceVim) for general discussion :)

EDIT: Sorry for openning issue which is not bug report nor feature request, just can not find your email address :)

**Comment by Xuyuanp** [comment]
OK
